name: Danger js
on: [pull_request]
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master # này là checkout code về máy
      - name: Use Node.js 18.x # sử dụng nodejs phiên bản 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Danger
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_TEST_PULL_REQUEST }}
